// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  carousel: dynamic(() => import("./Carousel")),
  content_index: dynamic(() => import("./ContentIndex")),
  faq: dynamic(() => import("./Faq")),
  features: dynamic(() => import("./Features")),
  footer_heading: dynamic(() => import("./FooterHeading")),
  footer_image: dynamic(() => import("./FooterImage")),
  footer_link_block: dynamic(() => import("./FooterLinkBlock")),
  footer_multi_column: dynamic(() => import("./FooterMultiColumn")),
  footer_rich_text: dynamic(() => import("./FooterRichText")),
  form: dynamic(() => import("./Form")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  process: dynamic(() => import("./Process")),
  rich_text: dynamic(() => import("./RichText")),
  testimonial: dynamic(() => import("./Testimonial")),
};
